#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $NEW_POSTGRES_USER CREATEDB CREATEROLE PASSWORD '$NEW_POSTGRES_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $NEW_POSTGRES_USER ;
	ALTER SCHEMA public OWNER TO $NEW_POSTGRES_USER;
EOSQL