version: '3.8'

services:
  postgresql:
    build: ./postgreSQL
    container_name: postgresql
    restart: always
    expose:
      - "5432"
    volumes:
      - type: bind
        source: ./postgre
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      NEW_POSTGRES_USER: ${NEW_POSTGRES_USER}
      NEW_POSTGRES_PASSWORD: ${NEW_POSTGRES_PASSWORD}
    networks:
      - intra
  nestjs:
    depends_on:
      - postgresql
    build: 
      context: ./nestjs
      dockerfile: dockerfile
    container_name: nestjs
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    expose:
      - "5432"
    volumes:
       - type: bind
         source: ./nestjs/transendence
         target: /home/node/app
    working_dir: /home/node/app
    command: "npm run start:dev"
    networks:
      - intra

networks:
  intra:
    driver: bridge
    name: intra
