cors:
  origin:
    - http://localhost*
    - https://localhost*
  method:
    - GET
    - HEAD
    - POST

auth:
  redirect_uri:
    - http://localhost*
    - https://localhost*

  source:
    intra42:
      key: 42
      auth_url: https://api.intra.42.fr/oauth/authorize
      token_url: https://api.intra.42.fr/oauth/token
      client_id: u-s4t2ud-a084cd305d97a248bad2bebb6e377a9f53307f0d0ec5b6c2c6d402f314b3978e
      client_secret: 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
      scope:
        - public
      openid: false
      subject_url: https://api.intra.42.fr/v2/me
      subject_key: id

    google:
      key: 100
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      jwks_url: https://www.googleapis.com/oauth2/v3/certs
      client_id: 000000000000-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      client_secret: GOCSPX-xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      scope:
        - https://www.googleapis.com/auth/userinfo.email
        - https://www.googleapis.com/auth/userinfo.profile
        - openid
      openid: true

  # openssl rand -base64 33
  jwt_secret: your-256-bit-secret

  jwt_expire_secs: 7200

  jwt_options:
    issuer: Akasha
